
from unittest import TestSuite
from unittest import main as unitTestMain

from os import linesep as osLineSep

from semantic_version import Version as SemanticVersion

from codeallybasic.UnitTestBase import UnitTestBase

from versionoverlord.Common import PackageName
from versionoverlord.Common import Packages
from versionoverlord.Common import UpdatePackage
from versionoverlord.IHandler import IHandler

REQUIREMENTS_STYLE: str = (
    f'click~=8.1.3{osLineSep}'
    f'ogl==0.70.20{osLineSep}'
    f'untangle~=1.2.1{osLineSep}'
)

EXPECTED_REQUIREMENTS_STYLE: str = (
    f'click~=9.0.0{osLineSep}'
    f'ogl==1.0.0{osLineSep}'
    f'untangle~=1.2.1{osLineSep}'
)

PY_PROJECT_TOML_STYLE: str = (
    f'dependencies = [{osLineSep}'
    f'  click<=8.1.3{osLineSep}'
    f'  ogl>=0.70.20{osLineSep}'
    f'  untangle==1.2.1{osLineSep}'
    f']{osLineSep}'
)

EXPECTED_PY_PROJECT_TOML_STYLE: str = (
    f'dependencies = [{osLineSep}'
    f'  click<=9.0.0{osLineSep}'
    f'  ogl>=1.0.0{osLineSep}'
    f'  untangle==1.2.1{osLineSep}'
    f']{osLineSep}'
)


class TestIHandler(UnitTestBase):
    """
    Auto generated by the one and only:
        Gato Malo – Humberto A. Sanchez II
        Generated: 04 March 2024
    """

    @classmethod
    def setUpClass(cls):
        super().setUpClass()

    def setUp(self):
        super().setUp()

    def tearDown(self):
        super().tearDown()

    def testUpdateStyleRequirementBasic(self):
        """
        Tests '==' and '~='
        """
        oglPackage: UpdatePackage = UpdatePackage(PackageName('ogl'),
                                                  oldVersion=SemanticVersion(version_string='0.70.20'),
                                                  newVersion=SemanticVersion(version_string='1.0.0')
                                                  )

        clickPackage: UpdatePackage = UpdatePackage(PackageName('click'),
                                                    oldVersion=SemanticVersion(version_string='8.1.3'),
                                                    newVersion=SemanticVersion(version_string='9.0.0')
                                                    )

        updatedContent: str = IHandler.updateDependencies(fileContent=REQUIREMENTS_STYLE, packages=Packages([oglPackage, clickPackage]))

        self.assertEqual(EXPECTED_REQUIREMENTS_STYLE, updatedContent, 'Not correctly updated')

        self.logger.info(f'{updatedContent}')

    def testUpdateStyleRequirementExtended(self):
        """
        Tests '=>=' and '<='
        """
        oglPackage: UpdatePackage = UpdatePackage(PackageName('ogl'),
                                                  oldVersion=SemanticVersion(version_string='0.70.20'),
                                                  newVersion=SemanticVersion(version_string='1.0.0')
                                                  )

        clickPackage: UpdatePackage = UpdatePackage(PackageName('click'),
                                                    oldVersion=SemanticVersion(version_string='8.1.3'),
                                                    newVersion=SemanticVersion(version_string='9.0.0')
                                                    )

        updatedContent: str = IHandler.updateDependencies(fileContent=PY_PROJECT_TOML_STYLE, packages=Packages([oglPackage, clickPackage]))

        self.assertEqual(EXPECTED_PY_PROJECT_TOML_STYLE, updatedContent, 'Not correctly updated')


def suite() -> TestSuite:
    import unittest

    testSuite: TestSuite = TestSuite()

    testSuite.addTest(unittest.defaultTestLoader.loadTestsFromTestCase(testCaseClass=TestIHandler))

    return testSuite


if __name__ == '__main__':
    unitTestMain()
